user1 = User.find_or_create_by(username: "Jaesar", first_name: "Zach")
user1.update(password:"password")
user2 = User.find_or_create_by(username: "MixMax", first_name: "Maks")
user2.update(password:"henry")
user3 = User.find_or_create_by(username: "badbitch69", first_name: "Stan")
user3.update(password:"StanRules")
Story.find_or_create_by(title: "fucked", content: "Lick butt and make a weird face immediately regret falling into bathtub. Experiences short bursts of poo-phoria after going to the loo cough furball into food bowl then scratch owner for a new one yet sleep all day whilst slave is at work, play all night whilst slave is sleeping, or carefully drink from water glass and then spill it everywhere and proceed to lick the puddle, yet sniff all the things. I like fish look at dog hiiiiiisssss or present belly, ")
Story.find_or_create_by(title: "doing weird things", content: "Howl uncontrollably for no reason leave buried treasure in the sandbox for the toddlers love you, then bite you yet the best thing in the universe is a cardboard box but put butt in owner's face please let me outside pouty face yay! ")
Story.find_or_create_by(title: "mom", content: "Sleep in the bathroom sink funny little cat chirrup noise shaking upright tail when standing next to you and nap all day, for do doodoo in the litter-box, clickityclack on the piano, be frumpygrumpy or toilet paper attack claws fluff everywhere meow miao french ciao litterbox yet thinking longingly about tuna brine and please stop looking at your phone and pet me. Friends are not food human give me attention meow yet meow all night. ")

